### ISSUE TITLE
Great finally something related to OODLE

### ISSUE THREAD

**Issue by kalasaceo** [hxhb/oodle-compression#1]
thanks man i have been studying your plugins since last year.i was wondering few days back how to use the oode compression to decrease apk size for android and today i saw it.
really thanks.
i cannot see documentation in your imzlp.com/posts/
could you please expalain a litte how to use it.would be great help.

**Comment by hxhb** [comment]
You can read this article as a reference https://imzlp.com/posts/8470/

**Comment by kalasaceo** [comment]
can you explain a little how to use it.i cannot see any new option regarding oodle compression in the project settings.should i use
-oodlecompression Selkie in compression option under project settings Packaging but could not see any difference in the resultant asset types.
i have added your oodle network and oodle data under the Plugins directory in engine source code.
am i doing something wrong
