### ISSUE TITLE
error when building oodle network under plugins directory in engine source

### ISSUE THREAD

**Issue by kalasaceo** [hxhb/oodle-compression#2]
hi Charlie Peng
this i the error i got when compiling yoiur oodledata and netword plugin
i have to delete the ue4 oodle at C:\UE4.24\Engine\Plugins\Runtime\PacketHandlers\CompressionComponents otherwise the engine code could not be generated after adding these plugins
here is the logs

1>------ Build started: Project: UE4, Configuration: Development_Editor x64 ------
1>Creating makefile for UE4Editor (no existing makefile)
1>Creating makefile for UnrealHeaderTool (no existing makefile)
1>Parsing headers for UE4Editor
1>  Running UnrealHeaderTool UE4Editor "C:\UE4.24\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors
1>Reflection code generated for UE4Editor in 173.26023 seconds
1>Creating makefile for ShaderCompileWorker (no existing makefile)
1>Building UE4Editor and ShaderCompileWorker...
1>Using Visual Studio 2017 14.16.27044 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.17763.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 10 actions with 8 processes...
1>  [1/10] PCH.OodleDataPlugin.cpp
1>  [2/10] PCH.OodleHandlerComponent.cpp
1>  [3/10] Module.OodleNetworkPlugin.gen.cpp
1>  [4/10] OodleDataPlugin.cpp
1>  [5/10] UE4Editor-OodleDataPlugin.lib
1>     Creating library C:\UE4.24\Engine\Plugins\OodleData\Intermediate\Build\Win64\UE4Editor\Development\OodleDataPlugin\UE4Editor-OodleDataPlugin.lib and object C:\UE4.24\Engine\Plugins\OodleData\Intermediate\Build\Win64\UE4Editor\Development\OodleDataPlugin\UE4Editor-OodleDataPlugin.exp
1>  [6/10] UE4Editor-OodleDataPlugin.dll
1>     Creating library C:\UE4.24\Engine\Plugins\OodleData\Intermediate\Build\Win64\UE4Editor\Development\OodleDataPlugin\UE4Editor-OodleDataPlugin.suppressed.lib and object C:\UE4.24\Engine\Plugins\OodleData\Intermediate\Build\Win64\UE4Editor\Development\OodleDataPlugin\UE4Editor-OodleDataPlugin.suppressed.exp
1>  [7/10] Module.OodleNetworkPlugin.cpp
1>C:/UE4.24/Engine/Plugins/OodleNetwork/Source/Private/OodleHandlerComponent.cpp(1673): error C2259: 'OodleHandlerComponent': cannot instantiate abstract class
1>  C:/UE4.24/Engine/Plugins/OodleNetwork/Source/Private/OodleHandlerComponent.cpp(1673): note: due to following members:
1>  C:/UE4.24/Engine/Plugins/OodleNetwork/Source/Private/OodleHandlerComponent.cpp(1673): note: 'void HandlerComponent::IncomingConnectionless(const TSharedPtr<const FInternetAddr,0> &,FBitReader &)': is abstract
1>  C:\UE4.24\Engine\Source\Runtime\PacketHandlers\PacketHandler\Public\PacketHandler.h(833): note: see declaration of 'HandlerComponent::IncomingConnectionless'
1>  C:/UE4.24/Engine/Plugins/OodleNetwork/Source/Private/OodleHandlerComponent.cpp(1673): note: 'void HandlerComponent::OutgoingConnectionless(const TSharedPtr<const FInternetAddr,0> &,FBitWriter &,FOutPacketTraits &)': is abstract
1>  C:\UE4.24\Engine\Source\Runtime\PacketHandlers\PacketHandler\Public\PacketHandler.h(862): note: see declaration of 'HandlerComponent::OutgoingConnectionless'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "UE4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**Comment by hxhb** [comment]
I fixed this error, you can try again after updating.

**Comment by kalasaceo** [comment]
can you explain a little how to use it.i cannot see any new option regarding oodle compression in the project settings.should i use
-oodlecompression Selkie in compression option under project settings Packaging but could not see any difference in the resultant asset types.
i have added your oodle network and oodle data under the Plugins directory in engine source code.
am i doing something wrong
